language: python
python:
  - "3.5"
install: "pip install -r requirements.txt"
script: tox
env:
  global:
    - REDISTOGO_URL=redis://localhost:6379
install:
  - pip install tox
services:
  - redis-server
